"""Everything the manuscript reads from the calibrated campaign suite:
LaTeX macros for every reported number, the result tables, and the data
figures - generated from `results/realistic/processed/*.csv`, never typed.

  python scripts/realistic/build_manuscript_inputs.py [--root results/realistic] [--paper paper_ibqn_v2]

Writes <paper>/tables/result_macros.tex, <paper>/tables/generated_*.tex and
copies <root>/figures/*.pdf into <paper>/figures/. Run `analyze_suite.py`
and `generate_figures.py` first.

Macro names are built from the table keys (`\\RFourLitLTwoRBFalseFeasRate`
= R04, literature hardware, planner L2-RB, false-feasibility rate); digits
are spelled out because TeX macro names are letters only. The full list,
with the CSV cell each macro came from, is written to
<paper>/tables/result_macros_provenance.csv.
"""
from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_ROOT = PROJECT_ROOT / "results" / "realistic"
DEFAULT_PAPER = PROJECT_ROOT / "paper_ibqn_v2"

DIGITS = {"0": "Zero", "1": "One", "2": "Two", "3": "Three", "4": "Four", "5": "Five", "6": "Six", "7": "Seven",
          "8": "Eight", "9": "Nine"}
HARDWARE = {"literature": "Lit", "theoretical_ops": "Ideal"}
PLANNER_NAMES = {"L1": "one-round", "L2": "iterative", "L2-R": "resource-aware (same-cycle)", "L2-RB": "resource-aware (buffered)",
                 "L3": "probabilistic", "L3-R": "probabilistic resource-aware (same-cycle)",
                 "L3-RB": "probabilistic resource-aware (buffered)", "L4": "simulation-in-the-loop"}


def macro_name(*parts) -> str:
    """CamelCase, letters only: `('R04', 'literature', 'L2-RB', 'rate')` ->
    `RZeroFourLitLTwoRBRate`... with the campaign prefix written by the
    caller as words (`RFour`) to keep names short."""
    out = []
    for part in parts:
        text = HARDWARE.get(str(part), str(part))
        text = re.sub(r"\d", lambda m: DIGITS[m.group()], text)
        words = re.split(r"[^A-Za-z]+", text)
        out.append("".join(word[:1].upper() + word[1:] for word in words if word))
    return "".join(out)


def fidelity_key(value: float) -> str:
    """0.705 -> 'F0705' (spelled out by `macro_name`)."""
    return "F" + f"{value:.3f}".replace(".", "").rstrip("0").ljust(3, "0")


class Macros:
    def __init__(self) -> None:
        self.rows: list[dict] = []

    def add(self, name: str, value: str, source: str) -> None:
        if any(row["macro"] == name for row in self.rows):
            raise ValueError(f"duplicate macro {name}")
        if not re.fullmatch(r"[A-Za-z]+", name):
            raise ValueError(f"invalid macro name {name!r}")
        self.rows.append(dict(macro=name, value=value, source=source))

    def count(self, name, value, source):
        self.add(name, "n/a" if pd.isna(value) else f"{int(round(float(value)))}", source)

    def percent(self, name, value, source, digits=1):
        self.add(name, "n/a" if pd.isna(value) else f"{100 * float(value):.{digits}f}\\%", source)

    def number(self, name, value, source, digits=1):
        self.add(name, "n/a" if pd.isna(value) else f"{float(value):.{digits}f}", source)

    def proportion(self, prefix, row, column, source):
        """count / of / rate / 95% CI of one Wilson-interval proportion."""
        self.count(prefix + "Count", row[f"{column}_count"], source)
        self.count(prefix + "Of", row[f"{column}_of"], source)
        self.percent(prefix + "Rate", row[f"{column}_rate"], source)
        self.percent(prefix + "CILow", row[f"{column}_ci_low"], source)
        self.percent(prefix + "CIHigh", row[f"{column}_ci_high"], source)

    def write(self, path: Path) -> None:
        lines = ["% Generated by scripts/realistic/build_manuscript_inputs.py - DO NOT EDIT BY HAND.",
                 "% Source: results/realistic/processed/*.csv (see result_macros_provenance.csv).", ""]
        lines += [f"\\newcommand{{\\{row['macro']}}}{{{row['value']}}}" for row in self.rows]
        path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        pd.DataFrame(self.rows).to_csv(path.with_name("result_macros_provenance.csv"), index=False)


def read(processed: Path, name: str) -> pd.DataFrame | None:
    path = processed / f"{name}.csv"
    return pd.read_csv(path) if path.exists() else None


# --------------------------------------------------------------------------
def physics_macros(m: Macros, processed: Path) -> None:
    """Closed-form reference points of the two hardware conditions, computed
    by the same code the planners use (`ibqn.physics`,
    `planning.planners.generation_models`) - not read from a results file."""
    import sys

    sys.path.insert(0, str(PROJECT_ROOT / "src"))
    from ibqn.experiments.realistic_suite import HARDWARE as PROFILES
    from ibqn.experiments.realistic_topologies import DEFAULT_LINK_M, realistic_chain
    from ibqn.network.capabilities import NetworkCapabilities
    from ibqn.network.platforms import resolve_platform
    from ibqn.planning.feasibility import estimate_swap_only_fidelity
    from ibqn.planning.planners.generation_models import attempt_cycle_s, estimate_generation, hop_success_probability

    for hardware, profile_name in PROFILES.items():
        profile = resolve_platform(profile_name)
        src = f"ibqn.physics on platform {profile_name}"
        for swaps in (1, 2, 3):
            spec = realistic_chain(swaps, platform=profile)
            capabilities = NetworkCapabilities(spec)
            route = [node.id for node in spec.nodes]
            fidelity, _ = estimate_swap_only_fidelity(capabilities, route)
            prefix = macro_name("Phys", hardware, f"Swaps{swaps}")
            m.number(prefix + "Fidelity", fidelity, src, 3)
            one_round = capabilities.physics.purification_between(route[0], route[-1])
            for rounds in (1, 2, 3):
                success, fidelity = one_round.improve(fidelity)
                m.number(prefix + macro_name(f"Rounds{rounds}") + "Fidelity", fidelity, src, 3)
                if rounds == 1:
                    m.percent(prefix + "RoundOneSuccess", success, src, 0)
            if hardware == "literature":
                slots = spec.nodes[0].memories
                m.number(macro_name("Phys", f"Swaps{swaps}", "BufferedRate"),
                         estimate_generation(capabilities, route, slots, model="buffered").raw_end_to_end_pair_rate, src, 0)
                m.number(macro_name("Phys", f"Swaps{swaps}", "SameCycleRate"),
                         estimate_generation(capabilities, route, slots, model="same_cycle").raw_end_to_end_pair_rate, src, 2)
    profile = resolve_platform(PROFILES["literature"])
    capabilities = NetworkCapabilities(realistic_chain(1, platform=profile))
    src = "generation_models on platform siv_2024, 5 km link"
    p = hop_success_probability(capabilities, "a", "r1")
    cycle = attempt_cycle_s(capabilities, "a", "r1")
    m.number("PhysAttemptSuccessPerMille", 1000 * p, src, 1)
    m.number("PhysAttemptCycleMicroseconds", 1e6 * cycle, src, 0)
    m.number("PhysPairsPerMemorySecond", p / cycle, src, 0)
    m.number("PhysLinkKilometres", DEFAULT_LINK_M / 1000, src, 0)
    for name, value, digits in (("RawFidelity", profile.raw_fidelity, 2), ("GateFidelity", profile.gate_fidelity, 3),
                                ("MeasurementFidelity", profile.measurement_fidelity, 3),
                                ("CoherenceSeconds", profile.coherence_time_s, 0), ("MemoryEfficiency", profile.memory_efficiency, 2),
                                ("DetectorEfficiency", profile.detector_efficiency, 1),
                                ("AttenuationDbPerKm", 1000 * profile.attenuation_db_per_m, 1),
                                ("CutoffSeconds", profile.cutoff_ratio * profile.coherence_time_s, 0)):
        m.number("Hw" + name, value, "network.platforms.SIV_2024", digits)


def audit_macros(m: Macros, processed: Path) -> None:
    integrity = read(processed, "r00_state_integrity_audit")
    if integrity is not None:
        row, src = integrity.iloc[0], "r00_state_integrity_audit.csv"
        m.count("AuditIntegrityRuns", row["runs"], src)
        m.count("AuditIntegrityAborted", row["aborted"], src)
        m.count("AuditIntegrityDangling", row["dangling_states_at_end"], src)
        m.count("AuditSwapInputs", sum(row[c] for c in integrity.columns if c.startswith("swap_input_")), src)
        m.count("AuditSwapInputsIntact", row["swap_input_ok"], src)
        m.count("AuditPurificationInputs", sum(row[c] for c in integrity.columns if c.startswith("purification_input_")), src)
        m.count("AuditPurificationInputsIntact", row["purification_input_ok"], src)
        m.count("AuditDecoherenceCalls", sum(row[c] for c in integrity.columns if c.startswith("decohere_")), src)
        m.count("AuditDecoherenceNoState", row["decohere_no_state"], src)
        m.count("AuditDecoherenceStale", row["decohere_stale_recreate"] + row["decohere_stale_overwrite"], src)
        m.count("AuditDecoherenceOverwrite", row["decohere_stale_overwrite"], src)
    generation = read(processed, "r00_generation_model_audit")
    if generation is not None:
        src = "r00_generation_model_audit.csv"
        forward = generation[~generation["reverse"].astype(bool)]
        multi = forward[forward["n_repeaters"] > 0]
        direct = forward[forward["n_repeaters"] == 0]
        m.count("AuditGenerationRuns", generation["runs"].sum(), src)
        m.count("AuditGenerationCells", len(multi), src)
        m.number("AuditBufferedPooledRatio", multi["delivered"].sum() / (multi["rate_model"] * multi["window"]).sum(), src, 3)
        m.percent("AuditBufferedMeanAbsError", (multi["measured/model"] - 1).abs().mean(), src)
        m.number("AuditBufferedMinRatio", multi["measured/model"].min(), src, 2)
        m.number("AuditBufferedMaxRatio", multi["measured/model"].max(), src, 2)
        m.number("AuditDirectPooledRatio", direct["delivered"].sum() / (direct["rate_model"] * direct["window"]).sum(), src, 3)
        m.number("AuditSameCycleMinFactor", multi["measured/same_cycle"].min(), src, 0)
        one_repeater = multi[multi["n_repeaters"] == 1]
        m.number("AuditSameCycleOneRepeaterFactor",
                 one_repeater["delivered"].sum() / (one_repeater["rate_same_cycle"] * one_repeater["window"]).sum(), src, 0)


def routing_macros(m: Macros, processed: Path) -> None:
    table = read(processed, "r02_routing")
    if table is None:
        return
    for _, row in table.iterrows():
        prefix = macro_name("RTwo", row["hardware"], row["topology"], row["routing_strategy"])
        src = f"r02_routing.csv[{row['hardware']},{row['topology']},{row['routing_strategy']}]"
        m.number(prefix + "Delivered", row["delivered_pairs_mean"], src)
        m.number(prefix + "Fidelity", row["average_fidelity_mean"], src, 3)
        m.percent(prefix + "SatisfiedRate", row["satisfied_rate"], src, 0)
        m.count(prefix + "Hops", row["hop_count"], src)
        m.count(prefix + "Seeds", row["seeds"], src)


def purification_macros(m: Macros, processed: Path) -> None:
    table = read(processed, "r03_purification_by_policy")
    if table is None:
        return
    for _, row in table.iterrows():
        prefix = macro_name("RThree", row["hardware"], row["topology"], fidelity_key(row["requested_fidelity"]),
                            row["purification_policy"])
        src = f"r03_purification_by_policy.csv[{row['hardware']},{row['topology']},{row['requested_fidelity']},{row['purification_policy']}]"
        m.count(prefix + "Seeds", row["seeds"], src)
        m.count(prefix + "Satisfied", row["n_satisfied"], src)
        m.count(prefix + "Violated", row["n_violated"], src)
        m.count(prefix + "Rejected", row["n_rejected"], src)
        m.number(prefix + "Delivered", row["delivered_pairs_mean"], src)
        m.number(prefix + "Fidelity", row["average_fidelity_mean"], src, 3)
        m.number(prefix + "Rounds", row["purification_rounds_mean"], src)
        m.number(prefix + "Discarded", row["discarded_pairs_mean"], src)


def planner_macros(m: Macros, processed: Path) -> None:
    quality = read(processed, "r04_planner_decision_quality")
    if quality is not None:
        for _, row in quality.iterrows():
            prefix = macro_name("RFour", row["hardware"], row["planner_level"])
            src = f"r04_planner_decision_quality.csv[{row['hardware']},{row['planner_level']}]"
            m.count(prefix + "Trials", row["trials"], src)
            m.count(prefix + "Satisfied", row["n_satisfied"], src)
            m.count(prefix + "Violated", row["n_violated"], src)
            m.count(prefix + "Rejected", row["n_rejected"], src)
            m.percent(prefix + "AdmittedRate", row["admitted_rate"], src)
            m.proportion(prefix + "FalseFeas", row, "false_feasibility", src)
            if "false_rejection_rate" in row:
                m.proportion(prefix + "FalseRej", row, "false_rejection", src)
    accuracy = read(processed, "r04_estimate_accuracy")
    if accuracy is not None:
        for _, row in accuracy.iterrows():
            prefix = macro_name("RFour", row["hardware"], row["planner_level"])
            src = f"r04_estimate_accuracy.csv[{row['hardware']},{row['planner_level']}]"
            m.number(prefix + "FidelityError", row["fidelity_error_mean"], src, 3)
            m.number(prefix + "DeliveredOverPredicted", row["delivered_over_predicted_no_purification"], src, 2)
    calibration = read(processed, "r04_l3_calibration")
    if calibration is not None:
        for _, row in calibration.iterrows():
            prefix = macro_name("RFour", row["hardware"], row["planner_level"])
            src = f"r04_l3_calibration.csv[{row['hardware']},{row['planner_level']}]"
            m.number(prefix + "Brier", row["brier_score"], src, 3)
            m.proportion(prefix + "ThresholdCorrect", row, "threshold_half_correct", src)
    for name, label in (("r04b_simulation_planner", "RFourB"), ("r04b_matched_grid", "RFourBMatched")):
        table = read(processed, name)
        if table is None:
            continue
        for _, row in table.iterrows():
            prefix = macro_name(label, row["hardware"], row["planner_level"])
            src = f"{name}.csv[{row['hardware']},{row['planner_level']}]"
            m.count(prefix + "Trials", row["trials"], src)
            m.count(prefix + "Satisfied", row["n_satisfied"], src)
            m.count(prefix + "Rejected", row["n_rejected"], src)
            m.proportion(prefix + "FalseFeas", row, "false_feasibility", src)
            m.number(prefix + "PlanningSeconds", row["planning_time_s_median"], src, 3 if row["planning_time_s_median"] < 1 else 1)


def reconciliation_macros(m: Macros, processed: Path) -> None:
    by_case = read(processed, "r06_reconciliation_by_case")
    if by_case is not None:
        for _, row in by_case.iterrows():
            prefix = macro_name("RSix", row["hardware"], row["case"])
            src = f"r06_reconciliation_by_case.csv[{row['hardware']},{row['case']}]"
            m.count(prefix + "Seeds", row["seeds"], src)
            m.count(prefix + "Violated", row["initial_violated"], src)
            m.count(prefix + "RejectedAtPlanning", row["initial_rejected"], src)
            m.proportion(prefix + "Recovered", row, "recovered", src)
            m.number(prefix + "EpisodeOnePairs", row["episode1_delivered_pairs_mean"], src)
            m.number(prefix + "EpisodeTwoPairs", row["episode2_delivered_pairs_mean"], src)
    by_action = read(processed, "r06_reconciliation_by_action")
    if by_action is not None:
        for _, row in by_action.iterrows():
            m.proportion(macro_name("RSix", row["hardware"], "action", row["action"], "Recovered"), row, "recovered",
                         f"r06_reconciliation_by_action.csv[{row['hardware']},{row['action']}]")


def baseline_macros(m: Macros, processed: Path) -> None:
    table = read(processed, "r01_architecture_baselines")
    if table is None:
        return
    for _, row in table.iterrows():
        prefix = macro_name("ROne", row["hardware"], row["condition"])
        src = f"r01_architecture_baselines.csv[{row['hardware']},{row['condition']}]"
        m.percent(prefix + "AcceptedRate", row["accepted_rate"], src, 0)
        m.percent(prefix + "SatisfiedRate", row["satisfied_rate"], src, 0)
        m.number(prefix + "Delivered", row["delivered_pairs_mean"], src)
        m.number(prefix + "Fidelity", row["average_fidelity_mean"], src, 3)
        m.number(prefix + "Episodes", row["episodes_mean"], src)
        m.count(prefix + "Seeds", row["seeds"], src)


def overhead_macros(m: Macros, processed: Path) -> None:
    table = read(processed, "r07_overhead")
    if table is None:
        return
    for _, row in table.iterrows():
        prefix = macro_name("RSeven", row["hardware"], row["condition"])
        src = f"r07_overhead.csv[{row['hardware']},{row['condition']}]"
        m.percent(prefix + "OverheadMedian", row["orchestration_overhead_ratio_median"], src, 2)
        m.percent(prefix + "OverheadMax", row["orchestration_overhead_ratio_max"], src, 2)
        m.percent(prefix + "PlanningShare", row["planning_overhead_ratio_median"], src, 3)
        m.number(prefix + "TotalSeconds", row["total_trial_wall_time_s_median"], src)
        m.count(prefix + "Seeds", row["seeds"], src)


def resource_macros(m: Macros, processed: Path) -> None:
    table = read(processed, "r08_resource_semantics")
    if table is None:
        return
    for _, row in table.iterrows():
        prefix = macro_name("REight", row["hardware"], f"S{int(row['reserved_memory_slots'])}",
                            f"T{int(round(row['duration_s'] * 1000))}ms")
        src = f"r08_resource_semantics.csv[{row['hardware']},{row['reserved_memory_slots']},{row['duration_s']}]"
        m.number(prefix + "Delivered", row["delivered_pairs_mean"], src)
        m.percent(prefix + "SatisfiedRate", row["satisfied_rate"], src, 0)
        m.number(prefix + "PairsPerSlotSecond", row["pairs_per_slot_second"], src, 0)


def multi_intent_macros(m: Macros, processed: Path) -> None:
    table = read(processed, "r09_multi_intent_by_scenario")
    if table is None:
        return
    for _, row in table.iterrows():
        prefix = macro_name("RNine", row["hardware"], row["scenario"], row["planner_level"])
        src = f"r09_multi_intent_by_scenario.csv[{row['hardware']},{row['scenario']},{row['planner_level']}]"
        for column in ("groups", "intents_submitted", "admitted", "satisfied", "violated", "failed"):
            m.count(prefix + macro_name(column), row[column], src)


# --------------------------------------------------------------------------
def planner_table(processed: Path) -> str | None:
    quality = read(processed, "r04_planner_decision_quality")
    if quality is None:
        return None
    has_oracle = "false_rejection_rate" in quality

    def cell(row, column):
        if pd.isna(row[f"{column}_rate"]):
            return "--"
        return (f"{int(row[f'{column}_count'])}/{int(row[f'{column}_of'])} ({100 * row[f'{column}_rate']:.0f}\\%) "
                f"[{100 * row[f'{column}_ci_low']:.0f}, {100 * row[f'{column}_ci_high']:.0f}]")

    lines = ["% Generated by scripts/realistic/build_manuscript_inputs.py - DO NOT EDIT BY HAND.",
             "\\begin{tabular}{llrrr" + ("l" if has_oracle else "") + "l}", "\\toprule",
             "Hardware & Model & Sat. & Viol. & Rej. & False feasibility [95\\% CI]"
             + (" & False rejection [95\\% CI]" if has_oracle else "") + " \\\\", "\\midrule"]
    for hardware, label in (("literature", "Literature"), ("theoretical_ops", "Ideal ops")):
        rows = quality[quality["hardware"] == hardware].set_index("planner_level")
        for i, level in enumerate([p for p in PLANNER_NAMES if p in rows.index]):
            row = rows.loc[level]
            lines.append(
                f"{label if i == 0 else ''} & {level} & {int(row['n_satisfied'])} & {int(row['n_violated'])} & "
                f"{int(row['n_rejected'])} & {cell(row, 'false_feasibility')}"
                + (f" & {cell(row, 'false_rejection')}" if has_oracle else "") + " \\\\")
        lines.append("\\midrule" if hardware == "literature" else "\\bottomrule")
    lines.append("\\end{tabular}")
    return "\n".join(lines) + "\n"


BUILDERS = [physics_macros, audit_macros, routing_macros, purification_macros, planner_macros, reconciliation_macros, baseline_macros,
            overhead_macros, resource_macros, multi_intent_macros]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT)
    parser.add_argument("--paper", type=Path, default=DEFAULT_PAPER)
    args = parser.parse_args()
    processed = args.root / "processed"
    tables, figures = args.paper / "tables", args.paper / "figures"
    tables.mkdir(parents=True, exist_ok=True)
    figures.mkdir(parents=True, exist_ok=True)

    macros = Macros()
    for build in BUILDERS:
        build(macros, processed)
    macros.write(tables / "result_macros.tex")
    print(f"wrote {len(macros.rows)} macros to {tables / 'result_macros.tex'}")

    table = planner_table(processed)
    if table is not None:
        (tables / "generated_planner_decision_quality.tex").write_text(table, encoding="utf-8")
        print("wrote generated_planner_decision_quality.tex")

    copied = 0
    for figure in sorted((args.root / "figures").glob("*.pdf")):
        shutil.copy2(figure, figures / figure.name)
        copied += 1
    print(f"copied {copied} figure(s) to {figures}")


if __name__ == "__main__":
    main()
