"""P-IBQN2b: generates every LaTeX table from the processed CSVs in
results/paper_ibqn/processed/ (built by generate_processed_data.py) -
never hardcodes a number directly in LaTeX. Each table file's header
comment records its source CSV(s) and the claim ID(s) it backs.

Run: python scripts/paper_ibqn/generate_tables.py
Writes: results/paper_ibqn/tables/*.tex
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[2]
PROCESSED_DIR = PROJECT_ROOT / "results" / "paper_ibqn" / "processed"
OUT_DIR = PROJECT_ROOT / "results" / "paper_ibqn" / "tables"

NA_DISPLAY = {
    "NA_NOT_APPLICABLE": "--",
    "NA_NOT_MEASURED": "not measured",
    "NA_NOT_COMPARABLE": "not comparable",
}


def esc(value) -> str:
    s = str(value)
    if s in NA_DISPLAY:
        return NA_DISPLAY[s]
    for a, b in [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("_", r"\_"), ("#", r"\#")]:
        s = s.replace(a, b)
    return s


def write_table(filename: str, caption: str, label: str, columns: list[str], header: list[str],
                 df: pd.DataFrame, source_csv: str, claim_note: str) -> None:
    lines = [
        f"% Generated by scripts/paper_ibqn/generate_tables.py - DO NOT EDIT BY HAND.",
        f"% Source: results/paper_ibqn/processed/{source_csv}",
        f"% {claim_note}",
        r"\begin{table}[t]",
        r"\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{{'l' * len(columns)}}}",
        r"\hline",
        " & ".join(header) + r" \\",
        r"\hline",
    ]
    for _, row in df.iterrows():
        cells = [esc(row[c]) for c in columns]
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\hline", r"\end{tabular}", r"\end{table}"]
    (OUT_DIR / filename).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT_DIR / filename} ({len(df)} data rows)")


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    # 1. intent_schema.tex
    df = pd.read_csv(PROCESSED_DIR / "intent_schema.csv")
    write_table(
        "intent_schema.tex", "Intent schema fields and their use across the lifecycle", "tab:intent_schema",
        ["field", "meaning", "used_by_validation", "used_by_planning", "used_by_assurance"],
        ["Field", "Meaning", "Used by validation", "Used by planning", "Used by assurance"],
        df, "intent_schema.csv", "Claims: C1, C4 (structural, code-inspection-derived).",
    )

    # 2. lifecycle_states.tex
    df = pd.read_csv(PROCESSED_DIR / "lifecycle_states.csv")
    write_table(
        "lifecycle_states.tex", "Intent lifecycle states", "tab:lifecycle_states",
        ["state", "meaning", "allowed_successors", "terminal", "evidence"],
        ["State", "Meaning", "Allowed successors", "Terminal?", "Evidence"],
        df, "lifecycle_states.csv", "Claims: C1, C2. ACTIVE->FAILED is a validation-discovered robustness correction, not original design.",
    )

    # 3. planner_capabilities.tex
    df = pd.read_csv(PROCESSED_DIR / "planner_capabilities.csv")
    write_table(
        "planner_capabilities.tex", "Planner capabilities", "tab:planner_capabilities",
        ["planner", "purification_model", "resource_awareness", "probability_model", "candidate_routes", "internal_simulation", "matched_grid"],
        ["Planner", "Purification model", "Resource awareness", "Probability model", "Candidate routes", "Internal simulation", "Matched grid?"],
        df, "planner_capabilities.csv",
        "Claims: C4, C13. L4 is not on the matched grid and is not an oracle. L1 shares a mechanism with, but is not the same code path as, F04's generic IntentPlanner.",
    )

    # 4. planner_false_feasibility.tex
    df = pd.read_csv(PROCESSED_DIR / "planner_error_results.csv")
    write_table(
        "planner_false_feasibility.tex", "Planner false-feasibility rates (admitted and operationally executed intents only)",
        "tab:planner_false_feasibility",
        ["planner", "denominator", "numerator", "rate"],
        ["Planner", "Admitted \\& executed", "Violated", "False-feasibility rate"],
        df, "planner_error_results.csv",
        "Claim: C6. Denominator excludes SIMULATION_ERROR/TIMEOUT trials that never reached assurance.",
    )

    # 5. oracle_purification_boundary.tex
    df = pd.read_csv(PROCESSED_DIR / "oracle_purification_boundary.csv")
    write_table(
        "oracle_purification_boundary.tex", "F04 offline-oracle purification-boundary experiment (NOT comparable to Table~\\ref{tab:oracle_by_planner})",
        "tab:oracle_purification_boundary",
        ["experiment", "planner_path", "rejected", "oracle_tested", "oracle_satisfiable", "rate"],
        ["Experiment", "Planner path", "Rejected", "Oracle tested", "Oracle satisfiable", "Rate"],
        df, "oracle_purification_boundary.csv",
        "Claim: C8. Deliberately constructed around the one-round purification ceiling; not used to rank planners.",
    )

    # 6. oracle_by_planner.tex
    df = pd.read_csv(PROCESSED_DIR / "oracle_by_planner.csv")
    write_table(
        "oracle_by_planner.tex", "Offline-oracle false-rejection rate by planner (P02b; NOT comparable to Table~\\ref{tab:oracle_purification_boundary})",
        "tab:oracle_by_planner",
        ["planner", "rejected", "oracle_tested", "oracle_satisfiable", "false_rejection_rate", "ci_low", "ci_high"],
        ["Planner", "Rejected", "Oracle tested", "Oracle satisfiable", "False-rejection rate", "CI low", "CI high"],
        df, "oracle_by_planner.csv", "Claim: C7.",
    )

    # 7. assurance_results.tex
    df = pd.read_csv(PROCESSED_DIR / "assurance_results.csv")
    write_table(
        "assurance_results.tex", "Assurance consistency by planner/campaign", "tab:assurance_results",
        ["planner_or_campaign", "executed_intents", "assurance_evaluations", "mismatches", "missing_evaluations", "status"],
        ["Planner/campaign", "Executed intents", "Assurance evaluations", "Mismatches", "Missing evaluations", "Status"],
        df, "assurance_results.csv",
        "Claim: C3. Rejected intents are excluded from 'executed intents' by design (evaluation=None), never counted as missing.",
    )

    # 8. reconciliation_results.tex
    df = pd.read_csv(PROCESSED_DIR / "reconciliation_results.csv")
    write_table(
        "reconciliation_results.tex", "Reconciliation outcomes by action (F05)", "tab:reconciliation_results",
        ["action", "triggered", "episode2_executed", "recovered", "failed_recovery", "recovery_rate"],
        ["Action", "Triggered", "Episode 2 executed", "Recovered", "Failed recovery", "Recovery rate"],
        df, "reconciliation_results.csv",
        "Claim: C9. Recovery means the second execution episode was evaluated as SATISFIED.",
    )

    # 9. multi_intent_results.tex
    df = pd.read_csv(PROCESSED_DIR / "multi_intent_results.csv")
    write_table(
        "multi_intent_results.tex", "Multi-intent campaign outcomes (P17)", "tab:multi_intent_results",
        ["scenario", "groups", "intents", "planner", "admitted", "satisfied", "reservation_rejected", "violated", "failed"],
        ["Scenario", "Groups", "Intents", "Planner", "Admitted", "Satisfied", "Reservation-rejected", "Violated", "Failed"],
        df, "multi_intent_results.csv",
        "Claims: C10, C11. 'Admitted' is the planner's decision; 'reservation-rejected' is a distinct, execution-time NetworkManager outcome.",
    )

    # 10. overhead_results.tex
    df = pd.read_csv(PROCESSED_DIR / "overhead_results.csv")
    write_table(
        "overhead_results.tex", "Wall-time decomposition (P17, median/P90, machine-dependent)", "tab:overhead_results",
        ["component", "median_s", "p90_s", "pct_of_total", "scope"],
        ["Component", "Median (s)", "P90 (s)", "\\% of total", "Scope"],
        df, "overhead_results.csv",
        "Claim: C12. route_application and true persistence cost are not isolated (marked not measured), never estimated.",
    )

    # 11. failure_taxonomy.tex
    df = pd.read_csv(PROCESSED_DIR / "failure_taxonomy.csv")
    write_table(
        "failure_taxonomy.tex", "Failure-class taxonomy", "tab:failure_taxonomy",
        ["failure_class", "definition", "example", "detected_by", "final_state"],
        ["Failure class", "Definition", "Example", "Detected by", "Final state"],
        df, "failure_taxonomy.csv", "Claims: C2, C6, C7, C8 (descriptive, not a single campaign result).",
    )

    # 12. limitations.tex
    df = pd.read_csv(PROCESSED_DIR / "limitations.csv")
    write_table(
        "limitations.tex", "Threats to validity and limitations", "tab:limitations",
        ["limitation", "claim_id"],
        ["Limitation", "Related claim(s)"],
        df, "limitations.csv", "Descriptive summary of Section 19's threats to validity.",
    )

    print("DONE")


if __name__ == "__main__":
    main()
